[phases.setup]
nixPkgs = ["nodejs-18_x", "postgresql"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci --only=production"]

[phases.build]
dependsOn = ["install"]
cmds = [
  "npm install --include=dev",
  "npx vite build",
  "npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist --external:vite --external:@vitejs/plugin-react --external:@replit/vite-plugin-runtime-error-modal --external:@replit/vite-plugin-cartographer --external:../vite.config --external:./vite --external:nanoid"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"